### ISSUE TITLE
The uicollection view can slide of vertical .

### ISSUE THREAD

**Issue by zakiso** [paweldudek/carousel-collection-view-layout#3] opened 2016-01-07 04:06 UTC
When I use a UICollectionView init with this layout 

```
PBDCarouselCollectionViewLayout *layout = [[PBDCarouselCollectionViewLayout alloc] init];
        CGSize size = CGSizeMake(self.frame.size.width-80, self.frame.size.height - 200);
        layout.itemSize = size;
        layout.interItemSpace = 10;

        _collectionView = [[UICollectionView alloc]initWithFrame:CGRectMake(0, 0, self.frame.size.width, self.frame.size.height)
                                            collectionViewLayout:layout];
```

The collection view item can scroll of vertical.How do I disable its sliding of vertical?
![image](http://7xkpss.com1.z0.glb.clouddn.com/66666.gif)

**Comment by paweldudek** [comment] 2016-01-07 11:27
@lazydeer this definitely should not behave like this, I'll take look at it.

**Comment by zakiso** [comment] 2016-01-07 11:42
Thanks your reply. I found change the code `CGFloat contentHeight = self.itemSize.height + 2 * self.topBottomMargin`  to `CGFloat contentHeight = self.itemSize.height`; The collectionView work fine.   But when itemSize height is to large ,the vertical scroll bar will appear.

**Comment by paweldudek** [comment] 2016-01-07 12:00
Yeah, the problem is that the `height` of your items is bigger than the height of collection itself, which triggers a bug in the `contentSize` calculation. 

I think that centring the cell if it's too big is a better idea (with an appropriate log to console). What do you think?

**Comment by zakiso** [comment] 2016-01-07 12:07
Yes I think so. And can you fix the bug? :)

**Comment by paweldudek** [comment] 2016-01-14 12:56
So vertical centering is implemented correctly, the problem is that when the collection view is embedded in a `UINavigationController` it has its `contentInset` set, which adds the additional scrolling (I'm not considering custom `contentInset` when calculating layout). 

I'll get a new version out that fixes this. Thanks for reporting!

**Comment by paweldudek** [comment] 2016-01-14 16:22
@lazydeer this has been fixed in master, you can point your `Podfile` to latest commit to get this resolved.

**Comment by paweldudek** [comment] 2016-01-14 17:42
And 1.1.0 is out with a fix for this issue.

**Closed as completed by paweldudek** 2016-01-14 17:42 UTC
Labels: bug
